run:
  skip-dirs:
    - testdata
    - poc
  deadline: 240s
  tests: true
  #modules-download-mode: vendor # for go.mod based

linters:
  disable-all: true
  enable:
    - govet
    #- revive
    #- varcheck
    #- structcheck
      #- errcheck
      #- staticcheck
      #- ineffassign
      #- unconvert
      #- goimports
      #- misspell
      #- lll
      #- nakedret
      #- gocritic

linters-settings:
  lll:
    line-length: 120
issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
      - staticcheck
      text: "SA5008:"
